name: synapse
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=12.1
  - jupyterlab
  - matplotlib
  - scikit-learn
  - numpy
  - tqdm
  - pyyaml
  - psutil
