# File: src/task_heads.py
"""
Task-Specific Heads for SynapseOS.

These modules define the final layers of the network for specific tasks
(e.g., classification, segmentation). Their weights are generated by the
TaskWeaver and applied dynamically.
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
from collections import OrderedDict

class BaseTaskHead(nn.Module):
    def __init__(self):
        super().__init__()
        # Layers will be defined in subclasses

    def get_parameter_shapes(self):
        """
        Returns an OrderedDict of parameter names and their shapes for this head.
        The TaskWeaver will generate weights matching these shapes.
        """
        shapes = OrderedDict()
        for name, param in self.named_parameters():
            # We only want parameters of the layers defined in this head
            # (not from any potential sub-modules if they were complex and had fixed weights)
            if '.' in name: # Indicates it's a parameter of a layer within this head
                 shapes[name] = param.shape
        
        # Detach all parameters, as they will be set externally by the TaskWeaver
        for p in self.parameters():
            p.requires_grad = False
        return shapes

    def apply_weights(self, weights_dict):
        """
        Applies externally generated weights to the layers of this head.
        Assumes weights_dict keys match the layer parameter names (e.g., 'layer1.weight').
        """
        with torch.no_grad():
            for name, param in self.named_parameters():
                if name in weights_dict:
                    if param.shape != weights_dict[name].shape:
                        raise ValueError(f"Shape mismatch for {name}: expected {param.shape}, got {weights_dict[name].shape}")
                    param.copy_(weights_dict[name])
                # else:
                #     print(f"Warning: Weight for {name} not found in provided weights_dict for head.")


class ClassificationHead(BaseTaskHead):
    def __init__(self, input_features_dim, num_classes, num_hidden_layers=0, hidden_dim=None):
        """
        A classification head, typically an MLP.

        Args:
            input_features_dim (int): Dimensionality of the input feature vector.
            num_classes (int): Number of output classes.
            num_hidden_layers (int): Number of hidden layers in the head's MLP.
            hidden_dim (int): Size of hidden layers if num_hidden_layers > 0.
        """
        super().__init__()
        self.layers = nn.ModuleList()
        current_dim = input_features_dim

        if num_hidden_layers > 0 and hidden_dim is None:
            raise ValueError("hidden_dim must be specified if num_hidden_layers > 0")

        for i in range(num_hidden_layers):
            self.layers.append(nn.Linear(current_dim, hidden_dim))
            # No ReLU here, as F.relu will be applied in forward if weights are set
            current_dim = hidden_dim
        
        self.output_layer = nn.Linear(current_dim, num_classes)

    def forward(self, x, head_weights):
        """
        Args:
            x (torch.Tensor): Input feature vector (B, input_features_dim).
            head_weights (OrderedDict): Weights for the layers in this head.
        """
        # Ensure x is flat
        if x.dim() > 2:
            x = torch.flatten(x, 1)

        for i, _ in enumerate(self.layers):
            w = head_weights[f'layers.{i}.weight']
            b = head_weights[f'layers.{i}.bias']
            x = F.relu(F.linear(x, w, b)) # Apply ReLU after linear for hidden layers

        w_out = head_weights['output_layer.weight']
        b_out = head_weights['output_layer.bias']
        x = F.linear(x, w_out, b_out)
        return x


class SegmentationHead(BaseTaskHead):
    def __init__(self, input_feature_channels, num_classes, intermediate_channels=256, upsample_factor=2):
        """
        A simple FCN-style segmentation head.

        Args:
            input_feature_channels (int): Number of channels in the input feature map from the backbone.
            num_classes (int): Number of segmentation classes.
            intermediate_channels (int): Number of channels in an intermediate conv layer.
            upsample_factor (int): Factor to upsample to reach target output size (depends on backbone stride).
                                   This is a simplified upsampling; a real FCN uses skip connections.
        """
        super().__init__()
        # Example: A 1x1 conv to predict classes, then upsample
        # More complex heads might have several conv/transposed_conv layers.
        self.conv_intermediate = nn.Conv2d(input_feature_channels, intermediate_channels, kernel_size=3, padding=1)
        self.conv_final = nn.Conv2d(intermediate_channels, num_classes, kernel_size=1)
        
        if upsample_factor > 1:
            self.upsample = nn.Upsample(scale_factor=upsample_factor, mode='bilinear', align_corners=False)
        else:
            self.upsample = nn.Identity()
            
    def forward(self, x_feature_map, head_weights):
        """
        Args:
            x_feature_map (torch.Tensor): Input feature map (B, C_in, H_feat, W_feat).
            head_weights (OrderedDict): Weights for the layers in this head.
        """
        # Apply intermediate conv
        w_inter = head_weights['conv_intermediate.weight']
        b_inter = head_weights['conv_intermediate.bias']
        x = F.relu(F.conv2d(x_feature_map, w_inter, b_inter, padding=self.conv_intermediate.padding))

        # Apply final class conv
        w_final = head_weights['conv_final.weight']
        b_final = head_weights['conv_final.bias']
        x = F.conv2d(x, w_final, b_final, padding=self.conv_final.padding)
        
        x = self.upsample(x)
        return x